package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemDO;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Jan 23 18:45:37 CST 2021
     */
    int insert(ItemDO record);

    List<ItemDO> listItem();

    ItemDO selectByPrimaryKey();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sat Jan 23 18:45:37 CST 2021
     */
    int insertSelective(ItemDO record);
}